{{- if .Values.azure.keyVault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    {{- include "common.annotations.standard" . | nindent 4 }}
    {{- with .Values.azure.keyVault.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.azure.keyVault.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "common.names.azure.keyVaultCredentials" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
    clientId: {{ .Values.azure.keyVault.clientId | b64enc }}
    clientSecret: {{ .Values.azure.keyVault.clientSecret | b64enc }}
{{- end }}