{{- if .Values.azure.csi.storageClass.enabled }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  annotations:
    {{- include "common.annotations.standard" . | nindent 4 }}
    {{- with .Values.azure.csi.storageClass.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.azure.csi.storageClass.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "common.names.azure.storageClass" . }}
provisioner: file.csi.azure.com
reclaimPolicy: {{ .Values.azure.csi.storageClass.reclaimPolicy }}
{{- with .Values.azure.csi.storageClass.mountOptions }}
mountOptions:
  {{- toYaml . | nindent 2 }}
{{- end }}
parameters:
    subscriptionID: {{ .Values.azure.csi.storageClass.subscriptionID }}
    resourceGroup: {{ .Values.azure.csi.storageClass.resourceGroup }}
    storageAccount: {{ .Values.azure.csi.storageClass.storageAccount }}
    shareName: {{ .Values.azure.csi.storageClass.shareName }}
{{- end }}