{{- if .Values.azure.keyVault.enabled }}
{{- $azureSecretStoreName := include "common.names.azure.keyVault" . -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    {{- include "common.annotations.standard" . | nindent 4 }}
    {{- with .Values.azure.keyVault.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.azure.keyVault.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "common.names.azure.keyVault" . }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.azure.keyVault.refreshInterval | default "1m" }}
  secretStoreRef:
    kind: SecretStore
    name: {{ $azureSecretStoreName }}
  target:
    name: {{ include "common.names.azure.keyVault" . }}
    creationPolicy: Owner
  data:
  {{- range $data := .Values.azure.keyVault.data }}
  - secretKey: {{ $data.secretKey }}
    remoteRef:
      key: {{ $data.key }}
  {{- end }}
{{- end }}