{{- if .Values.azure.keyVault.enabled }}
{{- $azureKeyvaultSecretName := include "common.names.azure.keyVaultCredentials" . -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  annotations:
    {{- include "common.annotations.standard" . | nindent 4 }}
    {{- with .Values.azure.keyVault.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.azure.keyVault.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "common.names.azure.keyVault" . }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      tenantId: {{ .Values.azure.keyVault.tenantId }}
      vaultUrl: {{ .Values.azure.keyVault.vaultUrl }}
      environmentType: PublicCloud
      authSecretRef: 
        clientId: 
          name: {{ $azureKeyvaultSecretName }}
          key: clientId
        clientSecret:
          name: {{ $azureKeyvaultSecretName }}
          key: clientSecret 
{{- end }}