{{- if .Values.azure.registry.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    {{- include "common.annotations.standard" . | nindent 4 }}
    {{- with .Values.secret.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "common.names.azure.registry" . }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "common.secrets.azure.registrySecrets" (dict "server" .Values.azure.registry.server "username" .Values.azure.registry.username "password" .Values.azure.registry.password) | quote }}
{{- end }}