{{- if and (.Values.aws.secretManager.enabled) (.Values.aws.secretManager.secretRef) }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    {{- include "common.annotations.standard" . | nindent 4 }}
    {{- with .Values.aws.secretManager.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.aws.secretManager.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "common.names.aws.secretManagerCredentials" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
    access-key: {{ .Values.aws.secretManager.secretRef.accessKey | b64enc }}
    secret-access-key: {{ .Values.aws.secretManager.secretRef.secretAccessKey | b64enc }}
{{- end }}