{{- if .Values.aws.secretManager.enabled }}
{{- $awsSecretManagerSecretName := include "common.names.aws.secretManagerCredentials" . -}}
{{- $awsSecretManagerServiceAccountName := include "common.names.aws.secretManager" . -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  annotations:
    {{- include "common.annotations.standard" . | nindent 4 }}
    {{- with .Values.aws.secretManager.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.aws.secretManager.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "common.names.aws.secretManager" . }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      {{- if .Values.aws.secretManager.roleArn }}
      role: {{ .Values.aws.secretManager.roleArn }}
      {{- end }}
      region: {{ .Values.aws.secretManager.region }}
      auth:
        {{- if .Values.aws.secretManager.secretRef }}
        secretRef:
          accessKeyIDSecretRef:
            name: {{ $awsSecretManagerSecretName }}
            key: access-key
          secretAccessKeySecretRef:
            name: {{ $awsSecretManagerSecretName }}
            key: secret-access-key
        {{- end }}
        {{- if .Values.aws.secretManager.jwt }}
        jwt:
          serviceAccountRef:
            name: {{ $awsSecretManagerServiceAccountName }}
        {{- end }}
{{- end }}