{{- if and (.Values.aws.secretManager.enabled) (.Values.aws.secretManager.jwt)}}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- include "common.annotations.aws.secretManager" . | nindent 4 }}
    {{- include "common.annotations.standard" . | nindent 4 }}
    {{- with .Values.aws.secretManager.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.aws.secretManager.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "common.names.aws.secretManager" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}