{{- if .Values.aws.secretManager.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    {{- include "common.annotations.standard" . | nindent 4 }}
    {{- with .Values.aws.secretManager.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.aws.secretManager.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "common.names.aws.secretManager" . }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.aws.secretManager.refreshInterval | default "1m" }}
  secretStoreRef:
    name: {{ include "common.names.aws.secretManager" . }}
    kind: SecretStore
  target:
    name: {{ include "common.names.aws.secretManager" . }}
    creationPolicy: Owner
  data:
  {{- range $data := .Values.aws.secretManager.data }}
  - secretKey: {{ $data.secretKey }}
    remoteRef:
      key: {{ $data.key }}
      property: {{ $data.property }} 
  {{- end }}
{{- end }}