{{- if .Values.keda.scaledObject.enabled}}
{{- $deploymentName := include "common.names.fullname" . -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  annotations:
    {{- include "common.annotations.standard" . | nindent 4 }}
    {{- with .Values.keda.scaledObject.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.keda.scaledObject.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $deploymentName }}
  minReplicaCount: {{ .Values.keda.scaledObject.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.scaledObject.maxReplicaCount }}
  pollingInterval: {{ .Values.keda.scaledObject.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.scaledObject.cooldownPeriod }}
  {{- range .Values.keda.scaledObject.triggers }}
  triggers:
    - type: {{ .type }}
      metadata:
        bootstrapServersFromEnv: {{ .bootstrapServersFromEnv }}
        consumerGroup: {{ .consumerGroup }}
        topic: {{ .topic }}
        lagThreshold: {{ .lagThreshold }}
        offsetResetPolicy: {{ .offsetResetPolicy }}
        version: {{ .version }}
        sasl: {{ .sasl }}
        tls: {{ .tls }}
        unsafeSasl: {{ .unsafeSasl }}
      authenticationRef:
        name: {{ .authenticationRef.name }}
  {{- end }}
{{- end }}