{{- if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    {{- include "common.annotations.standard" . | nindent 4 }}
    {{- with .Values.configMap.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.configMap.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.configMap.values }}
    {{- range $key, $value := .Values.configMap.values }}
    {{- $key | nindent 2 }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{- end }}