{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "common.names.fullname" . -}}
{{- $servicePort := .Values.ingress.servicePort -}}
{{- $secretName := include "common.names.ingress.certificateCredentials" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- include "common.annotations.standard" . | nindent 4 }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  {{- if .Values.ingress.defaultBackend.enabled }}
  defaultBackend:
    service:
      name: {{ $serviceName }}
      port:
        number: {{ $servicePort }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls: 
  {{- range .Values.ingress.tls.hosts }} 
  - hosts:
    - {{ .url }}
    secretName: {{ $secretName | default "default-tls" }}
  {{- end }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .url | quote }}
    http:
      paths:
      - path: {{ .path | default "/" }}
        pathType: {{ .pathType | default "Prefix" }}
        backend:
          service:
            name: {{ $serviceName }}
            port:
              number: {{ $servicePort }}
  {{- end }}
{{- end }}