{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    {{- include "common.annotations.standard" . | nindent 4 }}
    {{- with .Values.secret.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if .Values.secret.values }}
    {{- range $key, $value := .Values.secret.values }}
    {{- $key | nindent 2 }}: {{ $value | b64enc }}
    {{- end }}
  {{- end }}
{{- end }}