{{- if .Values.script.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    {{- include "common.annotations.standard" . | nindent 4 }}
    {{- with .Values.script.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.script.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "common.names.script" . }}
  namespace: {{ .Release.Namespace }}
data:
  {{- range .Values.script.values }}
  {{ .name }}: |
    {{- .data | nindent 4 }}
  {{- end }}  
{{- end }}