{{- if .Values.istio.virtualService.enabled }}
{{- $serviceName := include "common.names.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $istioGatewayName := include "common.names.istio.gateway" . -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
    {{- include "common.annotations.standard" . | nindent 4 }}
    {{- with .Values.istio.virtualService.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.istio.virtualService.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }} 
spec:
  hosts:
  {{- range .Values.istio.virtualService.hosts }} 
  - {{ .url }}
  {{- end }}
  gateways:
  - {{ $istioGatewayName }}
  http:
  {{- range .Values.istio.virtualService.destination }}
  - name: {{ .name }}
    match:
    - uri:
        prefix: {{ .uriPrefix }}
    rewrite:
      uri: {{ .rewriteUri }}
    route:
    - destination:
        host: {{ $serviceName }}
        port:
          number: {{ $servicePort }}
        subset: {{ .destinationsubset }}
  {{- end }}
{{- end }}